spring:
  profiles: dev
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 15
  client:
    # Doesn't register itself in eureka server
    register-with-eureka: false
    # Is determines if service register itself as a client in eureka server.
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
